### ISSUE TITLE
Initialization error (Unexpected token U in JSON at position 4)

### ISSUE THREAD

**Issue by borez** [onfoot/homebridge-shelly-switch#1]
Hi there,

Am trying your plugin as the other one (relying on CoAP) isn't working reliably.

I get the following errors when using your plugin. All accessories also disappear for some reason.

`[15/12/2020, 11:45:10] [Shelly Switch] Error parsing current status info: SyntaxError: Unexpected token U in JSON at position 4`

My config file is as follows:
```
 {
            "platform": "Shelly Switch",
            "notification_port": 54220,
            "name": "Shelly Switch",
            "devices": [
                {
                    "name": "xxx",
                    "ip": "192.168.x.x"
                },
                {
                    "name": "yyy",
                    "ip": "192.168.x.x"
                }
            ]
   }
```

Am running latest firmware 1.90 coupled with HB 1.24 (testing with HB 1.30 b32 didn't work too).

**Comment by onfoot** [comment]
Hey! Sorry to hear that. Can you check what you get in response when you open the offending shelly's http://`192.168.x.x`/relay/0 in your browser?

**Comment by borez** [comment]
Thanks for getting back!

The login error prompt clears after I set a user:pass on the offending device, and the accessory is properly displayed. However, I can't change the state of the device, with the following error message: 

```
[15/12/2020, 17:19:23] [Shelly Switch] Failed to change switch status: SyntaxError: Unexpected token U in JSON at position 4
[On@Homebridge 4022 98CD] The write handler for the characteristic 'On' on the accessory 'xxx' was slow to respond!

```
I get this on the offending device.

`{"ison":true,"has_timer":false,"timer_started":0,"timer_duration":0,"timer_remaining":0,"source":"input"}`

Going to my HB instance on port 54220 shows a "Not found" status.


EDIT: For some reason, I reinstalled the plugin and everything seems to work now? Running on HB 1.30 B32. Am also using I/O URL Actions on the Shellies.

**Comment by onfoot** [comment]
Huh, somehow the authentication parameters are not passed when setting the relay state. I'll get on it in a few hours and will release an update. Thanks for checking the plugin out!

**Comment by onfoot** [comment]
It took a little longer to fix, but there you go. 0.2.3 should talk to your authenticated shelly now.

Admittedly there are some issues with the devices hiding and appearing, most likely at first launch after changing devices in homebridge settings. I hope to get on it sometime soon.

**Comment by borez** [comment]
Thanks for this - 0.23 is definitely more stable now. 

BTW there are times where extra configured "button" profiles popping up in the Accessories tab. Although I'm using Shelly 1s, which don't have a button?

**Comment by onfoot** [comment]
Good to hear!

As for the buttons, you are able to connect a switch to Shelly 1, aren't you. ;) And if that switch is a doorbell-type one with a spring, it can be configured as a momentary button in Shelly, and thus able to be exposed in Home as a smart programmable button.

To give one example, I configured my staircase switch as one and if I long press it, all lights downstairs turn off.
