### ISSUE TITLE
Dimmers

### ISSUE THREAD

**Issue by woodgieboodgie** [onfoot/homebridge-shelly-switch#2]
Thanks for your work on this.  It has worked perfectly for Shelly 1.
Will this plugin work for Shelly dimmers?

**Comment by benlaniado** [comment]
Thank you for this amazing plugin.
I also have Shelly Dimmer 2. 
It has a different API `/light/0/?turn=on&brightness=76`.
A played with your code and saw it can be quite easy enabling support for dimmer.
I thought I could add `deviceType: dimmer` to the configuration of the device.
What do you think? Should I create a PR for it?

**Comment by onfoot** [comment]
Hi! I'm glad you found it useful (almost). ;)

If you are able to make sure the plugin will work with your changes, then a PR is most welcome! The app essentially autodetects the features of the switches, so maybe the "deviceType" option wouldn't be necessary. I'd need to take a look at dimmer's API, how to recognize one using its status response.

I don't have any dimmers to test it on unfortunately.

**Comment by benland** [comment]
I open a PR.
I have Shelly 1L and Shelly Dimmer 2 and it works great with both of them now.

**Comment by benland** [comment]
https://github.com/onfoot/homebridge-shelly-switch/pull/3
